#R code to produce plot2.png
plotData<-read.table("household_power_consumption.txt",header=TRUE,sep = ";")
plotData$Date<-as.Date(plotData$Date,"%d/%m/%Y")
subplotData<-subset(plotData,Date >="2007-02-01"& Date <="2007-02-02")
subplotData$Global_active_power <-as.numeric(as.character(subplotData$Global_active_power))
subplotData$Date<-paste(subplotData$Date,subplotData$Time)
subplotData$Date<-strptime(subplotData$Date,"%Y-%m-%d %H:%M:%S")
png(file = "plot2.png",width = 480, height = 480, units = "px")
with(subplotData,plot(Date,Global_active_power,type = "l",ylab = "Global Active Power(kilowatts)",xlab = ""))
dev.off()