#R code to produce plot3.png
plotData<-read.table("household_power_consumption.txt",header=TRUE,sep = ";")
plotData$Date<-as.Date(plotData$Date,"%d/%m/%Y")
subplotData<-subset(plotData,Date >="2007-02-01"& Date <="2007-02-02")
subplotData$Sub_metering_1 <-as.numeric(as.character(subplotData$Sub_metering_1))
subplotData$Sub_metering_2 <-as.numeric(as.character(subplotData$Sub_metering_2))
subplotData$Sub_metering_3 <-as.numeric(as.character(subplotData$Sub_metering_3))
subplotData$Date<-paste(subplotData$Date,subplotData$Time)
subplotData$Date<-strptime(subplotData$Date,"%Y-%m-%d %H:%M:%S")
png(file = "plot3.png",width = 480, height = 480, units = "px")
with(subplotData,{plot(Date,Sub_metering_1,type = "l",col="black",ylab = "Energy sub metering")
  lines(Date,Sub_metering_2,type = "l",col="red")
  lines(Date,Sub_metering_3,type = "l",col="blue")
  legend("topright", lty=1, col = c("black", "blue", "red"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3" ))
} )
dev.off()