#R code to produce plot4.png
plotData<-read.table("household_power_consumption.txt",header=TRUE,sep = ";")
plotData$Date<-as.Date(plotData$Date,"%d/%m/%Y")
subplotData<-subset(plotData,Date >="2007-02-01"& Date <="2007-02-02")
subplotData$Global_active_power <-as.numeric(as.character(subplotData$Global_active_power))
subplotData$Voltage <-as.numeric(as.character(subplotData$Voltage))
subplotData$Sub_metering_1 <-as.numeric(as.character(subplotData$Sub_metering_1))
subplotData$Sub_metering_2 <-as.numeric(as.character(subplotData$Sub_metering_2))
subplotData$Sub_metering_3 <-as.numeric(as.character(subplotData$Sub_metering_3))
subplotData$Global_reactive_power <-as.numeric(as.character(subplotData$Global_reactive_power))
subplotData$Date<-paste(subplotData$Date,subplotData$Time)
subplotData$Date<-strptime(subplotData$Date,"%Y-%m-%d %H:%M:%S")
png(file = "plot4.png",width = 480, height = 480, units = "px")
par(mfrow=c(2,2))
with(subplotData,{
  plot(Date,Global_active_power,type = "l",col="black",ylab = "Global Active Power",xlab = "")
  plot(Date,Voltage,type = "l",col="black",ylab = "Volage",xlab = "datetime")
})
with(subplotData,{
  plot(Date,Sub_metering_1,type = "l",col="black",ylab = "Energy sub metering",xlab = "")
  lines(Date,Sub_metering_2,type = "l",col="red")
  lines(Date,Sub_metering_3,type = "l",col="blue")
  legend("topright", lty=1, col = c("black", "blue", "red"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3" ))
})
with(subplotData,plot(Date,Global_reactive_power,type = "l",xlab = "datetime"))
dev.off()
